package com.broadengate.vcms.entity;




import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Keyword generated by hbm2java
 */
@Entity
@Table(name="keyword"
    ,catalog="vcms"
)
public class Keyword  implements java.io.Serializable {


     private Integer wordId;
     private String wordName;
     private Date createTime;
     private Integer videoNum;
     private Set<VideoInfo> videoInfos = new HashSet<VideoInfo>(0);

    public Keyword() {
    }

	
    public Keyword(Integer wordId) {
        this.wordId = wordId;
    }
    public Keyword(Integer wordId, String wordName, Date createTime, Integer videoNum, Set<VideoInfo> videoInfos) {
       this.wordId = wordId;
       this.wordName = wordName;
       this.createTime = createTime;
       this.videoNum = videoNum;
       this.videoInfos = videoInfos;
    }
   
    @Id 
    @GeneratedValue(strategy = IDENTITY)
    @Column(name="WORD_ID", unique=true, nullable=false)
    public Integer getWordId() {
        return this.wordId;
    }
    
    public void setWordId(Integer wordId) {
        this.wordId = wordId;
    }
    
    @Column(name="WORD_NAME", length=64)
    public String getWordName() {
        return this.wordName;
    }
    
    public void setWordName(String wordName) {
        this.wordName = wordName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_TIME", length=0)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="VIDEO_NUM")
    public Integer getVideoNum() {
        return this.videoNum;
    }
    
    public void setVideoNum(Integer videoNum) {
        this.videoNum = videoNum;
    }
    @ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER, mappedBy="keywords")
    public Set<VideoInfo> getVideoInfos() {
        return this.videoInfos;
    }
    
    public void setVideoInfos(Set<VideoInfo> videoInfos) {
        this.videoInfos = videoInfos;
    }




}


