package com.broadengate.vcms.entity;

// default package
// Generated 2009-7-15 10:27:13 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Playlist generated by hbm2java
 */
@Entity
@Table(name = "playlist", catalog = "vcms")
public class Playlist implements java.io.Serializable {

	private Integer listId;
	private String listName;
	private Date startTime;
	private Date endTime;
	private Date createTime;
	private String playState;
	private Integer videoNum;
	private Set<PlayListShip> playListShips = new HashSet<PlayListShip>(0);
	private Set<TermPlaylist> termPlaylists = new HashSet<TermPlaylist>(0);

	public Playlist() {
	}

	public Playlist(String playState) {
		this.playState = playState;
	}

	public Playlist(String listName,Date startTime,Date endTime, Date createTime, String playState,
			Integer videoNum, Set<PlayListShip> playListShips,
			Set<TermPlaylist> termPlaylists) {
		this.listName = listName;
		this.startTime = startTime;
		this.endTime = endTime;
		this.createTime = createTime;
		this.playState = playState;
		this.videoNum = videoNum;
		this.playListShips = playListShips;
		this.termPlaylists = termPlaylists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LIST_ID", unique = true, nullable = false)
	public Integer getListId() {
		return this.listId;
	}

	public void setListId(Integer listId) {
		this.listId = listId;
	}

	@Column(name = "LIST_NAME", length = 128)
	public String getListName() {
		return this.listName;
	}

	public void setListName(String listName) {
		this.listName = listName;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_TIME", length = 0)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_TIME", length = 0)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 0)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "PLAY_STATE", nullable = false, length = 6)
	public String getPlayState() {
		return this.playState;
	}

	public void setPlayState(String playState) {
		this.playState = playState;
	}

	@Column(name = "VIDEO_NUM")
	public Integer getVideoNum() {
		return this.videoNum;
	}

	public void setVideoNum(Integer videoNum) {
		this.videoNum = videoNum;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "playlist")
	public Set<PlayListShip> getPlayListShips() {
		return this.playListShips;
	}

	public void setPlayListShips(Set<PlayListShip> playListShips) {
		this.playListShips = playListShips;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "playlist")
	public Set<TermPlaylist> getTermPlaylists() {
		return this.termPlaylists;
	}

	public void setTermPlaylists(Set<TermPlaylist> termPlaylists) {
		this.termPlaylists = termPlaylists;
	}

}
