package com.broadengate.vcms.entity;

// default package
// Generated 2009-7-15 10:27:13 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlayListShip generated by hbm2java
 */
@Entity
@Table(name = "play_list_ship", catalog = "vcms")
public class PlayListShip implements java.io.Serializable {

	private Integer shipId;
	private Playlist playlist;
	private VideoInfo videoInfo;
	private Date createTime;
	private String listSeq;

	public PlayListShip() {
	}

	public PlayListShip(Playlist playlist, VideoInfo videoInfo,
			Date createTime, String listSeq) {
		this.playlist = playlist;
		this.videoInfo = videoInfo;
		this.createTime = createTime;
		this.listSeq = listSeq;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SHIP_ID", unique = true, nullable = false)
	public Integer getShipId() {
		return this.shipId;
	}

	public void setShipId(Integer shipId) {
		this.shipId = shipId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LIST_ID")
	public Playlist getPlaylist() {
		return this.playlist;
	}

	public void setPlaylist(Playlist playlist) {
		this.playlist = playlist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VIDEO_ID")
	public VideoInfo getVideoInfo() {
		return this.videoInfo;
	}

	public void setVideoInfo(VideoInfo videoInfo) {
		this.videoInfo = videoInfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 0)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "LIST_SEQ")
	public String getListSeq() {
		return this.listSeq;
	}

	public void setListSeq(String listSeq) {
		this.listSeq = listSeq;
	}

}
