package com.broadengate.vcms.entity;
// default package
// Generated 2009-7-15 10:27:13 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TargetGroup generated by hbm2java
 */
@Entity
@Table(name = "target_group", catalog = "vcms")
public class TargetGroup implements java.io.Serializable {

	private int groupId;
	private String groupName;
	private Date createTime;
	private String descn;
	private Set<TermInfo> termInfos = new HashSet<TermInfo>(0);

	public TargetGroup() {
	}

	public TargetGroup(int groupId) {
		this.groupId = groupId;
	}

	public TargetGroup(int groupId, String groupName, Date createTime,
			String descn, Set<TermInfo> termInfos) {
		this.groupId = groupId;
		this.groupName = groupName;
		this.createTime = createTime;
		this.descn = descn;
		this.termInfos = termInfos;
	}

	@Id
	@Column(name = "GROUP_ID", unique = true, nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "GROUP_NAME", length = 64)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 0)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "DESCN", length = 2000)
	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinTable(name = "term_target_group", catalog = "vcms", joinColumns = { @JoinColumn(name = "GROUP_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "TERM_ID", nullable = false, updatable = false) })
	public Set<TermInfo> getTermInfos() {
		return this.termInfos;
	}

	public void setTermInfos(Set<TermInfo> termInfos) {
		this.termInfos = termInfos;
	}

}
