package com.broadengate.vcms.entity;

// default package
// Generated 2009-7-15 10:27:13 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TermType generated by hbm2java
 */
@Entity
@Table(name = "term_type", catalog = "vcms")
public class TermType implements java.io.Serializable {

	private Integer typeId;
	private String typeName;
	private String descn;
	private Set<TermInfo> termInfos = new HashSet<TermInfo>(0);

	public TermType() {
	}

	public TermType(String typeName, String descn, Set<TermInfo> termInfos) {
		this.typeName = typeName;
		this.descn = descn;
		this.termInfos = termInfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TYPE_ID", unique = true, nullable = false)
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@Column(name = "TYPE_NAME", length = 128)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "DESCN")
	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "termType")
	public Set<TermInfo> getTermInfos() {
		return this.termInfos;
	}

	public void setTermInfos(Set<TermInfo> termInfos) {
		this.termInfos = termInfos;
	}

}
