package com.broadengate.vcms.entity;

// default package
// Generated 2009-7-15 10:27:13 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TermInfo generated by hbm2java
 */
@Entity
@Table(name = "term_info", catalog = "vcms")
public class TermInfo implements java.io.Serializable {

	private Integer termId;
	private TermType termType;
	private String termName;
	private String termAddr;
	private String termDec;
	private String termIp;
	private String termMask;
	private String termGateway;
	private String termDns;
	private String termScale;
	private String termResolution;
	private String termScreen;
	private String termRoot;
	private String termNum;
	private Integer termActivation;
	private String termInitialscreen;
	private Integer termCom;
	private Date termLastLogintime;
	private Date createTime;
	private Set<TermPlaylist> termPlaylists = new HashSet<TermPlaylist>(0);
	private Set<TargetGroup> targetGroups = new HashSet<TargetGroup>(0);

	public TermInfo() {
	}

	public TermInfo(String termNum, Date createTime) {
		this.termNum = termNum;
		this.createTime = createTime;
	}

	public TermInfo(TermType termType, String termName, String termAddr,
			String termDec, String termIp, String termMask, String termGateway,
			String termDns, String termScale, String termResolution,
			String termScreen, String termRoot, String termNum,
			Integer termActivation, String termInitialscreen, Integer termCom,
			Date termLastLogintime, Date createTime,
			Set<TermPlaylist> termPlaylists, Set<TargetGroup> targetGroups) {
		this.termType = termType;
		this.termName = termName;
		this.termAddr = termAddr;
		this.termDec = termDec;
		this.termIp = termIp;
		this.termMask = termMask;
		this.termGateway = termGateway;
		this.termDns = termDns;
		this.termScale = termScale;
		this.termResolution = termResolution;
		this.termScreen = termScreen;
		this.termRoot = termRoot;
		this.termNum = termNum;
		this.termActivation = termActivation;
		this.termInitialscreen = termInitialscreen;
		this.termCom = termCom;
		this.termLastLogintime = termLastLogintime;
		this.createTime = createTime;
		this.termPlaylists = termPlaylists;
		this.targetGroups = targetGroups;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TERM_ID", unique = true, nullable = false)
	public Integer getTermId() {
		return this.termId;
	}

	public void setTermId(Integer termId) {
		this.termId = termId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TYPE_ID")
	public TermType getTermType() {
		return this.termType;
	}

	public void setTermType(TermType termType) {
		this.termType = termType;
	}

	@Column(name = "TERM_NAME", length = 128)
	public String getTermName() {
		return this.termName;
	}

	public void setTermName(String termName) {
		this.termName = termName;
	}

	@Column(name = "TERM_ADDR", length = 128)
	public String getTermAddr() {
		return this.termAddr;
	}

	public void setTermAddr(String termAddr) {
		this.termAddr = termAddr;
	}

	@Column(name = "TERM_DEC", length = 128)
	public String getTermDec() {
		return this.termDec;
	}

	public void setTermDec(String termDec) {
		this.termDec = termDec;
	}

	@Column(name = "TERM_IP", length = 16)
	public String getTermIp() {
		return this.termIp;
	}

	public void setTermIp(String termIp) {
		this.termIp = termIp;
	}

	@Column(name = "TERM_MASK", length = 16)
	public String getTermMask() {
		return this.termMask;
	}

	public void setTermMask(String termMask) {
		this.termMask = termMask;
	}

	@Column(name = "TERM_GATEWAY", length = 16)
	public String getTermGateway() {
		return this.termGateway;
	}

	public void setTermGateway(String termGateway) {
		this.termGateway = termGateway;
	}

	@Column(name = "TERM_DNS", length = 16)
	public String getTermDns() {
		return this.termDns;
	}

	public void setTermDns(String termDns) {
		this.termDns = termDns;
	}

	@Column(name = "TERM_SCALE", length = 10)
	public String getTermScale() {
		return this.termScale;
	}

	public void setTermScale(String termScale) {
		this.termScale = termScale;
	}

	@Column(name = "TERM_RESOLUTION", length = 10)
	public String getTermResolution() {
		return this.termResolution;
	}

	public void setTermResolution(String termResolution) {
		this.termResolution = termResolution;
	}

	@Column(name = "TERM_SCREEN", length = 1024)
	public String getTermScreen() {
		return this.termScreen;
	}

	public void setTermScreen(String termScreen) {
		this.termScreen = termScreen;
	}

	@Column(name = "TERM_ROOT", length = 1024)
	public String getTermRoot() {
		return this.termRoot;
	}

	public void setTermRoot(String termRoot) {
		this.termRoot = termRoot;
	}

	@Column(name = "TERM_NUM", nullable = false, length = 36)
	public String getTermNum() {
		return this.termNum;
	}

	public void setTermNum(String termNum) {
		this.termNum = termNum;
	}

	@Column(name = "TERM_ACTIVATION")
	public Integer getTermActivation() {
		return this.termActivation;
	}

	public void setTermActivation(Integer termActivation) {
		this.termActivation = termActivation;
	}

	@Column(name = "TERM_INITIALSCREEN", length = 1024)
	public String getTermInitialscreen() {
		return this.termInitialscreen;
	}

	public void setTermInitialscreen(String termInitialscreen) {
		this.termInitialscreen = termInitialscreen;
	}

	@Column(name = "TERM_COM")
	public Integer getTermCom() {
		return this.termCom;
	}

	public void setTermCom(Integer termCom) {
		this.termCom = termCom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TERM_LAST_LOGINTIME", length = 0)
	public Date getTermLastLogintime() {
		return this.termLastLogintime;
	}

	public void setTermLastLogintime(Date termLastLogintime) {
		this.termLastLogintime = termLastLogintime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 0)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "termInfo")
	public Set<TermPlaylist> getTermPlaylists() {
		return this.termPlaylists;
	}

	public void setTermPlaylists(Set<TermPlaylist> termPlaylists) {
		this.termPlaylists = termPlaylists;
	}

	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "termInfos")
	public Set<TargetGroup> getTargetGroups() {
		return this.targetGroups;
	}

	public void setTargetGroups(Set<TargetGroup> targetGroups) {
		this.targetGroups = targetGroups;
	}

}
