package com.broadengate.vcms.entity;

// default package
// Generated 2009-7-15 10:27:13 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TermPlaylist generated by hbm2java
 */
@Entity
@Table(name = "term_playlist", catalog = "vcms")
public class TermPlaylist implements java.io.Serializable {

	private Integer termListId;
	private Playlist playlist;
	private TermInfo termInfo;
	private Date createTime;

	public TermPlaylist() {
	}

	public TermPlaylist(Playlist playlist, TermInfo termInfo, Date createTime) {
		this.playlist = playlist;
		this.termInfo = termInfo;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TERM_LIST_ID", unique = true, nullable = false)
	public Integer getTermListId() {
		return this.termListId;
	}

	public void setTermListId(Integer termListId) {
		this.termListId = termListId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LIST_ID")
	public Playlist getPlaylist() {
		return this.playlist;
	}

	public void setPlaylist(Playlist playlist) {
		this.playlist = playlist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TERM_ID")
	public TermInfo getTermInfo() {
		return this.termInfo;
	}

	public void setTermInfo(TermInfo termInfo) {
		this.termInfo = termInfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 0)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
