package com.broadengate.vcms.entity;

// default package
// Generated 2009-7-15 10:27:13 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VideoAlbumShipId generated by hbm2java
 */
@Embeddable
public class VideoAlbumShipId implements java.io.Serializable {

	private Integer albumId;
	private Integer videoId;
	private Integer albumSeq;
	private Date createTime;

	public VideoAlbumShipId() {
	}

	public VideoAlbumShipId(Integer albumId, Integer videoId, Integer albumSeq,
			Date createTime) {
		this.albumId = albumId;
		this.videoId = videoId;
		this.albumSeq = albumSeq;
		this.createTime = createTime;
	}

	@Column(name = "ALBUM_ID")
	public Integer getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	@Column(name = "VIDEO_ID")
	public Integer getVideoId() {
		return this.videoId;
	}

	public void setVideoId(Integer videoId) {
		this.videoId = videoId;
	}

	@Column(name = "ALBUM_SEQ")
	public Integer getAlbumSeq() {
		return this.albumSeq;
	}

	public void setAlbumSeq(Integer albumSeq) {
		this.albumSeq = albumSeq;
	}

	@Column(name = "CREATE_TIME", length = 0)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VideoAlbumShipId))
			return false;
		VideoAlbumShipId castOther = (VideoAlbumShipId) other;

		return ((this.getAlbumId() == castOther.getAlbumId()) || (this
				.getAlbumId() != null
				&& castOther.getAlbumId() != null && this.getAlbumId().equals(
				castOther.getAlbumId())))
				&& ((this.getVideoId() == castOther.getVideoId()) || (this
						.getVideoId() != null
						&& castOther.getVideoId() != null && this.getVideoId()
						.equals(castOther.getVideoId())))
				&& ((this.getAlbumSeq() == castOther.getAlbumSeq()) || (this
						.getAlbumSeq() != null
						&& castOther.getAlbumSeq() != null && this
						.getAlbumSeq().equals(castOther.getAlbumSeq())))
				&& ((this.getCreateTime() == castOther.getCreateTime()) || (this
						.getCreateTime() != null
						&& castOther.getCreateTime() != null && this
						.getCreateTime().equals(castOther.getCreateTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAlbumId() == null ? 0 : this.getAlbumId().hashCode());
		result = 37 * result
				+ (getVideoId() == null ? 0 : this.getVideoId().hashCode());
		result = 37 * result
				+ (getAlbumSeq() == null ? 0 : this.getAlbumSeq().hashCode());
		result = 37
				* result
				+ (getCreateTime() == null ? 0 : this.getCreateTime()
						.hashCode());
		return result;
	}

}
